export { SurfaceDocuments } from './documents.js'
export { defaultHudSurface, defaultGlassMinimalSurface, defaultFieldsSurface, defaultDiagnosticsSurface, SEEDED_SURFACES } from './defaults.js'
export { compileQuery, resolveQueryScope, type QuerySources } from './query.js'
export { ItemSignalStore } from './signals.js'
export { firstRunNotice, type SetupData } from './setup/view.js'
export { renderSurfaceEditorPage, defaultBlockFor, blockTypeNames, blockRowHtml, type SurfaceEditorData } from './setup/surface-editor.js'
export { renderSettingsPage, type SettingsData } from './settings/shell.js'
export { SECTIONS, sectionById, defaultSectionId, GROUP_ORDER, type SettingsSection } from './settings/registry.js'
export { buildLedger, type LedgerPass, type LedgerHop, type LedgerExtras } from './settings/sections/ledger.js'
export { buildTrace, buildTraceInputs, type TraceData, type TraceInput, type TraceHop, type TraceTrail, type TraceRecords } from './settings/sections/trace.js'
export { evaluateSenseGates, requiredScreenSenseSlots, type CaptureSense, type ScreenSenseSlot, type SenseGate, type SenseGateChain, type SenseGateInput } from './settings/sense-gates.js'
