/**
 * The menu-bar (tray) icon, embedded as a base64 PNG so the shell ships no binary asset and the icon
 * stays diffable. A macOS TEMPLATE image: black glyph + alpha only (a ring — openinfo's "o"), which
 * macOS auto-tints for light/dark menu bars when the shell calls `image.setTemplateImage(true)`.
 * 16px @1x and 32px @2x for Retina. Generated by tools/genicon (kept out of the build; see README).
 */
export const TRAY_ICON_TEMPLATE_1X =
  'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAf0lEQVR4nK2Tyw3AIAxD3yAswiAM0rUYpIswSCuhHFIDLSpYyiU4Ic4HxohAMosvvAYHUIBLrNjbEAE4O4Fqp3EbzAT7JE3ZnpDll2A+z3nIKRI8QpaeVETJ3NXnKvHcOp0kzi94btqSYFkCq01kxxhZXSR2rLKX8+uYFFPnfAMQunOJI1+6/wAAAABJRU5ErkJggg=='

export const TRAY_ICON_TEMPLATE_2X =
  'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAA5klEQVR4nNVX0Q2FIAy8QVjEQRyERRiEQVjEQTQmkCihUIq88i7hS+id9AoF+EPsABwAnw0Xv03BFklO5vBxzTBMJ3FJiJGS39t5DJCncUhSs39AnA+2iBnkbBGmY9vDowJCRzqqnmgZ7g5giSAmfmv9gKfIt48czamcYonWFpGqK+iOJ84bgZafXqg53wrIEyy3Ilxlovgki2upuO45kcpXGCBPoEr05QNKgMR8OVixlxXwsxSom1C9DKF9EGGFo1j9MmqpPmdfx1ihIYF2SzZThKgzVmvLE1QfJk+oPc1KUHmcTsMF8T7NzMErCk0AAAAASUVORK5CYII='

/** Decode a base64 PNG to a Buffer (the shell hands these to nativeImage). */
export const trayIconBuffer = (base64: string): Buffer => Buffer.from(base64, 'base64')
