/** The HTTP surface, as data. phase = when it goes live. Client/workbench generate from this. */
export interface RouteDef {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE'
  path: string
  request?: string   // schema $id
  response: string   // schema $id or '<name>[]'
  phase: 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7
}

export const Routes: readonly RouteDef[] = [
  { method: 'GET', path: '/health', response: 'Health', phase: 0 },
  { method: 'GET', path: '/contracts', response: 'string[]', phase: 0 },
  { method: 'GET', path: '/contracts/:name', response: 'JsonSchema', phase: 0 },
  { method: 'GET', path: '/flags', response: 'Flag[]', phase: 0 },
  { method: 'PUT', path: '/flags/:key', request: 'Flag', response: 'Flag', phase: 0 },
  { method: 'GET', path: '/fabric', response: 'Fabric', phase: 1 },
  { method: 'PUT', path: '/fabric', request: 'Fabric', response: 'Fabric', phase: 1 },
  { method: 'GET', path: '/fabric/profiles', response: 'FabricProfile[]', phase: 2 },
  { method: 'GET', path: '/fabric/profiles/:id', response: 'FabricProfile', phase: 2 },
  { method: 'PUT', path: '/fabric/profiles/:id', request: 'FabricProfile', response: 'FabricProfile', phase: 2 },
  { method: 'DELETE', path: '/fabric/profiles/:id', response: 'FabricProfile', phase: 2 },
  { method: 'POST', path: '/fabric/profiles/:id/clone', request: 'CloneProfileRequest', response: 'FabricProfile', phase: 2 },
  { method: 'POST', path: '/fabric/profiles/:id/activate', response: 'FabricProfile', phase: 2 },
  { method: 'GET', path: '/fabric/secrets', response: 'SecretRef[]', phase: 2 },
  { method: 'PUT', path: '/fabric/secrets/:ref', request: 'SecretValue', response: 'SecretRef', phase: 2 },
  { method: 'DELETE', path: '/fabric/secrets/:ref', response: 'SecretRef', phase: 2 },
  { method: 'POST', path: '/fabric/test', request: 'Endpoint', response: 'EndpointProbe', phase: 2 },
  { method: 'GET', path: '/fabric/discover', response: 'DiscoverResult', phase: 2 },
  { method: 'POST', path: '/fabric/scan', request: 'ScanRequest', response: 'ScanResult', phase: 3 },
  { method: 'GET', path: '/fabric/local/models', response: 'LocalModelStatus[]', phase: 2 },
  { method: 'POST', path: '/fabric/local/download', request: 'LocalDownloadRequest', response: 'LocalModelStatus', phase: 2 },
  { method: 'POST', path: '/capture/:source', request: 'CaptureChunk', response: 'Ack', phase: 1 },
  { method: 'GET', path: '/workspaces', response: 'Workspace[]', phase: 1 },
  { method: 'GET', path: '/sessions', response: 'Session[]', phase: 2 },
  { method: 'POST', path: '/sessions', request: 'StartSessionRequest', response: 'Session', phase: 2 },
  { method: 'POST', path: '/sessions/:id/end', response: 'Session', phase: 2 },
  { method: 'GET', path: '/layouts/surfaces', response: 'Surface[]', phase: 3 },
  { method: 'GET', path: '/layouts/surfaces/:id', response: 'Surface', phase: 2 },
  { method: 'PUT', path: '/layouts/surfaces/:id', request: 'Surface', response: 'Surface', phase: 2 },
  { method: 'GET', path: '/modes', response: 'Mode[]', phase: 2 },
  { method: 'GET', path: '/modes/:id', response: 'Mode', phase: 4 },
  { method: 'PUT', path: '/modes/:id', request: 'Mode', response: 'Mode', phase: 2 },
  { method: 'GET', path: '/registers', response: 'Register[]', phase: 2 },
  { method: 'GET', path: '/registers/:id', response: 'Register', phase: 4 },
  { method: 'PUT', path: '/registers/:id', request: 'Register', response: 'Register', phase: 4 },
  { method: 'GET', path: '/templates', response: 'PromptTemplate[]', phase: 4 },
  { method: 'GET', path: '/templates/:id', response: 'PromptTemplate', phase: 4 },
  { method: 'PUT', path: '/templates/:id', request: 'PromptTemplate', response: 'PromptTemplate', phase: 4 },
  { method: 'GET', path: '/moments', response: 'Moment[]', phase: 2 },
  { method: 'GET', path: '/entities', response: 'Entity[]', phase: 2 },
  { method: 'GET', path: '/relevant', response: 'RelevantEntity[]', phase: 2 },
  { method: 'GET', path: '/drafts', response: 'Draft[]', phase: 2 },
  { method: 'GET', path: '/todos', response: 'TodoList[]', phase: 4 },
  { method: 'GET', path: '/todos/:id', response: 'TodoList', phase: 4 },
  { method: 'PUT', path: '/todos/:id', request: 'TodoList', response: 'TodoList', phase: 4 },
  { method: 'GET', path: '/workflows', response: 'WorkflowSpec[]', phase: 4 },
  { method: 'GET', path: '/workflows/:id', response: 'WorkflowSpec', phase: 4 },
  { method: 'PUT', path: '/workflows/:id', request: 'WorkflowSpec', response: 'WorkflowSpec', phase: 4 },
  { method: 'GET', path: '/bundles', response: 'Bundle[]', phase: 4 },
  { method: 'GET', path: '/bundles/:id', response: 'Bundle', phase: 4 },
  { method: 'PUT', path: '/bundles/:id', request: 'Bundle', response: 'Bundle', phase: 4 },
  { method: 'POST', path: '/query', request: 'BlockQuery', response: 'QueryResult', phase: 2 },
  { method: 'POST', path: '/chat', request: 'ChatRequest', response: 'ChatReply', phase: 4 },
  { method: 'GET', path: '/chat/history', response: 'ChatHistory', phase: 4 },
  { method: 'POST', path: '/item-signals', request: 'ItemSignal', response: 'ItemSignal', phase: 4 },
  { method: 'POST', path: '/recall', request: 'BlockQuery', response: 'QueryResult', phase: 3 },
  { method: 'POST', path: '/sessions/:id/reroute', request: 'RerouteRequest', response: 'Session', phase: 3 },
  { method: 'GET', path: '/pins', response: 'Pin[]', phase: 3 },
  { method: 'POST', path: '/pins', request: 'Pin', response: 'Pin', phase: 3 },
  { method: 'POST', path: '/pins/:id/ingest', response: 'Pin', phase: 4 },
  { method: 'GET', path: '/pins/:id/chunks', response: 'PinChunk[]', phase: 4 },
  { method: 'GET', path: '/teach/candidates', response: 'HintCandidate[]', phase: 4 },
  { method: 'POST', path: '/teach/entity', request: 'EntityCorrection', response: 'Entity', phase: 4 },
  { method: 'GET', path: '/hints', response: 'WorkspaceHints[]', phase: 4 },
  { method: 'GET', path: '/hints/:workspaceId', response: 'WorkspaceHints', phase: 4 },
  { method: 'PUT', path: '/hints/:workspaceId', request: 'WorkspaceHints', response: 'WorkspaceHints', phase: 4 },
  { method: 'GET', path: '/ledger', response: 'Commitment[]', phase: 4 },
  { method: 'PUT', path: '/ledger/:id', request: 'Commitment', response: 'Commitment', phase: 4 },
  { method: 'GET', path: '/queue', response: 'QueueStatus', phase: 3 },
  { method: 'GET', path: '/senses', response: 'SenseGateChain[]', phase: 4 },
  { method: 'GET', path: '/screen/results', response: 'OcrResult[]', phase: 4 },
  { method: 'GET', path: '/screen/status', response: 'ScreenStatus', phase: 4 },
] as const
